In [2]:
import pandas as pd 
import numpy as np

In [3]:
df = pd.read_csv('https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv')

In [4]:
df.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0


In [35]:
a = np.arange(5,-1)
a

array([], dtype=int64)

In [6]:
b = (10 +(a *2)) **2/100

In [7]:
b > b

array([False, False, False, False, False])

In [43]:
a = np.array([1,2,3])
c= np.array([4,5,6])
b = np.array([
    [1,2,3],
    [2,4,6]
])
a
b
b.dot(c)

array([32, 64])

In [44]:
d= np.random.rand(3,5)

In [46]:
b.dot(d)

array([[2.42872207, 3.76656682, 1.70745093, 3.25416148, 1.71489467],
       [4.85744414, 7.53313364, 3.41490187, 6.50832296, 3.42978934]])